[python]
version = "3.10"

[server]
headless = true
enableCORS = false
port = 8501

[theme]
base="light"
primaryColor="#4CAF50"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"
