[python]
version = "3.10"

[server]
headless = true
enableCORS = false
port = 8501

# .streamlit/config.toml
[theme]
base="light"
primaryColor="#4CAF50"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#E0E0E0"
textColor="#262730"
font="sans serif"
